/* ─── ITEM CATALOGUE ─────────────────────────────────────────────────────── */
// category: "weapon" | "armor" | "gear" | "consumable" | "magical"

export const ITEMS = [
  /* ── Starting Equipment ─────────────────────────────────────────────── */
  // Oakshield Warrior
  {name:"Ironwood Club",desc:"1d6+1 dmg, Close, two-handed",category:"weapon",tags:["melee","two-handed"]},
  {name:"Acorn-Cap Shield",desc:"1 free defense re-roll per combat",category:"armor",tags:["shield","defense"]},
  {name:"Bark Plate Armour",desc:"-1 all incoming damage, Worn",category:"armor",tags:["heavy","worn"]},
  {name:"Iron-Bond Oath Token",desc:"Allies within Close get +1 to Presence rolls",category:"gear",tags:["support","social"]},
  {name:"War Rations (3 days)",desc:"Sustains one character for 3 days",category:"consumable",tags:["food","survival"]},
  // Briar Rogue
  {name:"Thorn Daggers ×2",desc:"1d6 each, Close, concealable, dual-wield capable",category:"weapon",tags:["melee","dual","concealable"]},
  {name:"Sling + 10 Stones",desc:"1d6, Near range, silent with care",category:"weapon",tags:["ranged","silent"]},
  {name:"Grapple-Vine",desc:"10ft rope, Agility 4+ to use offensively",category:"gear",tags:["climbing","utility"]},
  {name:"Shadow-Cloak",desc:"+1d6 Stealth in dim or dark environments",category:"armor",tags:["stealth","cloak"]},
  {name:"Forged Guild Sigil",desc:"Opens underworld contacts in most settlements",category:"gear",tags:["social","underworld"]},
  // Grove Shaman
  {name:"Twisted Root Staff",desc:"1d6, Close, ritual focus (required for Storm Seed)",category:"weapon",tags:["melee","focus","two-handed"]},
  {name:"Ritual Herb Pouch",desc:"5 uses, +1d6 to any single Insight roll; refills on long rest",category:"consumable",tags:["magic","insight"]},
  {name:"Spirit-Drum",desc:"Required for Spirit Call; audible 3 zones away",category:"gear",tags:["magic","ritual"]},
  {name:"Bone Amulet",desc:"Immune to the first Poisoned condition each session",category:"armor",tags:["protection","poison"]},
  {name:"Seed-Rattle",desc:"Commune with plant spirits; Insight 4+ for local information",category:"gear",tags:["magic","ritual"]},
  // Canopy Ranger
  {name:"Shortbow",desc:"1d6+1, Near or Far range (Far without Eagle Eye: -1d6)",category:"weapon",tags:["ranged","bow"]},
  {name:"Thorn-Tipped Arrows ×20",desc:"Standard ammo, recoverable after combat",category:"consumable",tags:["ranged","ammo"]},
  {name:"Twin Bark-Knives",desc:"1d6 each, Close, dual-wield once per combat for +1d6",category:"weapon",tags:["melee","dual"]},
  {name:"Wilderness Pack",desc:"5 days rations, 30ft rope, fire-kit, first-aid moss (1 HP, 3 uses)",category:"gear",tags:["survival","bundle"]},
  {name:"Beast-Bond Charm",desc:"Required for the Beast Bond class ability",category:"gear",tags:["magic","ranger"]},
  // Gilded Herald
  {name:"Polished Acorn Medallion",desc:"Once per session, one ally auto-succeeds any single Presence roll",category:"gear",tags:["support","magic","presence"]},
  {name:"Persuasion Kit",desc:"Forged letters, noble seal, faction crest; opens restricted doors in any city",category:"gear",tags:["social","forgery"]},
  {name:"Throwing Knives ×3",desc:"1d6, Near range, concealable",category:"weapon",tags:["ranged","thrown","concealable"]},
  {name:"Voice Horn",desc:"Audible 5 zones; first blast causes Frightened unless target passes Wits 4+",category:"gear",tags:["support","fear"]},
  {name:"Formal Travelling Cloak",desc:"+1d6 to Persuade and Charm rolls in courts and settlements",category:"armor",tags:["social","cloak"]},
  // Folk gear
  {name:"City Travel Cloak",desc:"Blends into urban environments; +1d6 to blend-in checks",category:"armor",tags:["social","cloak"]},
  {name:"Forged City Pass",desc:"Grants access to most restricted city districts",category:"gear",tags:["social","forgery"]},
  {name:"Common Tool Kit",desc:"Hammer, nails, chisel, wedge — handle most repair tasks without a roll",category:"gear",tags:["utility","crafting"]},
  {name:"Carved Bone Totem",desc:"Ritual focus for Redpelt folk; +1 Insight for grove-related rolls",category:"gear",tags:["magic","ritual","redpelt"]},
  {name:"Bark-Fibre Armour",desc:"-1 incoming damage, lightweight",category:"armor",tags:["light","worn"]},
  {name:"Hunting Knife",desc:"1d6, Close range, one-handed",category:"weapon",tags:["melee","concealable"]},
  {name:"Dark Hooded Cloak",desc:"+1d6 Stealth in dim or dark environments",category:"armor",tags:["stealth","cloak"]},
  {name:"Smoke-Seed Pouch",desc:"3 uses; creates an obscuring cloud filling one zone for 2 rounds",category:"consumable",tags:["tactical","stealth"]},
  {name:"Lock-Pick Twig Set",desc:"Cunning 4+ to open non-magical locks",category:"gear",tags:["utility","rogue"]},
  {name:"Wind-Silk Glide-Cloak",desc:"Enables Glide ability; destroyed if torn",category:"armor",tags:["flying","glideborn"]},
  {name:"Messenger Satchel",desc:"Waterproof; holds 10 items without adding bulk",category:"gear",tags:["utility","carry"]},
  {name:"Sky-Map Scroll",desc:"Accurate map of the current region; auto-succeed navigation outdoors",category:"gear",tags:["navigation","glideborn"]},
  {name:"Bone-Rune Reading Pouch",desc:"Insight 4+ to read portents about near-future events",category:"gear",tags:["magic","ritual","palewhisker"]},
  {name:"White Hooded Travelling Cloak",desc:"Marks wearer as Palewhisker; +1 Presence with superstitious NPCs",category:"armor",tags:["social","cloak","palewhisker"]},
  {name:"Spirit-Candle",desc:"3 charges; reveals spirits and hidden magical auras in Close range",category:"consumable",tags:["magic","ritual"]},

  /* ── 50 Additional Common Items ─────────────────────────────────────── */
  {name:"Lantern",desc:"Burns 4 hours; illuminates 1 zone fully",category:"gear",tags:["light","utility"]},
  {name:"Rope (30ft)",desc:"Hemp rope; Agility 4+ for offensive use in climbing",category:"gear",tags:["utility","climbing"]},
  {name:"Tinderbox",desc:"Start fires reliably; 10 uses before refill needed",category:"gear",tags:["utility","survival"]},
  {name:"Bedroll",desc:"Sleep anywhere without penalty to next-day recovery rolls",category:"gear",tags:["survival","rest"]},
  {name:"Waterskin (full)",desc:"2 days' water supply for one character",category:"consumable",tags:["survival","water"]},
  {name:"Rations (1 day)",desc:"Sustains one character for one day",category:"consumable",tags:["food","survival"]},
  {name:"Bandages",desc:"Heal 1 HP; 3 uses per pack",category:"consumable",tags:["healing","survival"]},
  {name:"Healing Poultice",desc:"Restore 1d6 HP; single use",category:"consumable",tags:["healing","magic"]},
  {name:"Antidote Moss",desc:"Cure one Poisoned condition instantly; 2 uses",category:"consumable",tags:["healing","poison"]},
  {name:"Torches ×3",desc:"Illuminates 1 zone; lasts 1 hour each",category:"consumable",tags:["light","survival"]},
  {name:"Iron Rations (5 days)",desc:"Preserved hard-tack; heavy but long-lasting",category:"consumable",tags:["food","survival"]},
  {name:"Fishing Line & Hook",desc:"Catch fish in nearby water; Wits 4+ for a meal",category:"gear",tags:["survival","utility"]},
  {name:"Climber's Claws",desc:"+1d6 to all climbing and grip rolls",category:"gear",tags:["climbing","utility"]},
  {name:"Mud Camouflage",desc:"+1d6 Stealth outdoors; washes off in rain or water",category:"consumable",tags:["stealth","survival"]},
  {name:"Spyglass",desc:"Observe details at Far range without penalty",category:"gear",tags:["scouting","utility"]},
  {name:"Signal Mirror",desc:"Communicate up to 5 zones in direct sunlight",category:"gear",tags:["utility","communication"]},
  {name:"Mapping Kit",desc:"Create accurate maps; Wits 4+ when mapping new regions",category:"gear",tags:["navigation","utility"]},
  {name:"Herbalist Pouch",desc:"Identify plants and fungi without a roll in natural areas",category:"gear",tags:["nature","survival"]},
  {name:"Surgeon's Kit",desc:"Stabilise a Downed ally without a roll; 3 uses",category:"consumable",tags:["healing","medical"]},
  {name:"Trap Kit ×2",desc:"Set in a zone; Cunning 4+ to hide; triggers on first creature to enter",category:"gear",tags:["tactical","cunning"]},
  {name:"Smoke Canister",desc:"Fill one zone with thick smoke for 2 rounds; sight-based rolls at -1d6",category:"consumable",tags:["tactical","stealth"]},
  {name:"Grappling Hook",desc:"Attach rope to any surface up to Near range with Agility 4+",category:"gear",tags:["climbing","utility"]},
  {name:"Crowbar",desc:"+1d6 Brawn for forcing locked doors or prying objects",category:"gear",tags:["utility","brawn"]},
  {name:"Thieves' Tools",desc:"Cunning 4+ to open non-magical locks or disable simple traps",category:"gear",tags:["utility","rogue","cunning"]},
  {name:"Disguise Kit",desc:"Presence 4+ to pass as a different folk or occupation",category:"consumable",tags:["social","stealth","cunning"]},
  {name:"Ink & Quill",desc:"Write letters and documents with a steady hand",category:"gear",tags:["utility","social"]},
  {name:"Wax Seal Kit",desc:"Create official-looking seals; Cunning 4+ to forge faction stamps",category:"gear",tags:["social","forgery"]},
  {name:"Climbing Pitons ×6",desc:"Anchor rope to rock or bark surfaces; no roll required",category:"gear",tags:["climbing","utility"]},
  {name:"Snowshoes",desc:"No movement penalty in deep snow, bog, or loose mud",category:"gear",tags:["survival","movement"]},
  {name:"Short Sword",desc:"1d6, Close range, one-handed",category:"weapon",tags:["melee","versatile"]},
  {name:"Hand Axe",desc:"1d6, Close or Near range (thrown), one-handed",category:"weapon",tags:["melee","thrown"]},
  {name:"Spear",desc:"1d6+1, Close or Near range, two-handed",category:"weapon",tags:["melee","reach","two-handed"]},
  {name:"Quarterstaff",desc:"1d6, Close range; once per combat: +1 to any defense roll",category:"weapon",tags:["melee","two-handed","defense"]},
  {name:"Net",desc:"Entangle one target; Brawn 4+ to escape; Near range",category:"weapon",tags:["control","ranged","thrown"]},
  {name:"Caltrops",desc:"Scatter in one zone; enemies pay +1 action to cross",category:"gear",tags:["tactical","control"]},
  {name:"War Horn",desc:"Alert allies within 5 zones; signals auto-arrive within a scene",category:"gear",tags:["communication","support"]},
  {name:"Buckler Shield",desc:"Once per combat: negate 1 incoming damage",category:"armor",tags:["shield","defense"]},
  {name:"Leather Vest",desc:"Reduce all incoming damage by 1; light and quiet",category:"armor",tags:["light","worn","defense"]},
  {name:"Chain Shirt",desc:"Reduce damage by 2; noisy (-1d6 Stealth while worn)",category:"armor",tags:["medium","worn","defense","noisy"]},
  {name:"Hooded Cloak",desc:"+1d6 Stealth in crowds, forests, or low light",category:"armor",tags:["stealth","cloak"]},
  {name:"Crampons",desc:"No penalty on ice, wet bark, or slick surfaces",category:"gear",tags:["survival","movement"]},
  {name:"Magnifying Lens",desc:"+1d6 to detailed inspection or close-range Wits checks",category:"gear",tags:["utility","wits"]},
  {name:"Compass",desc:"Never become lost outdoors; navigation auto-succeeds in wilderness",category:"gear",tags:["navigation","survival"]},
  {name:"Healer's Herbs",desc:"Spend an action; one target heals 1 HP; 5 uses",category:"consumable",tags:["healing","nature"]},
  {name:"Smelling Salts",desc:"Instantly revive an unconscious ally; 2 uses",category:"consumable",tags:["healing","emergency"]},
  {name:"Poison Vial",desc:"Coat one weapon; deal +1d6 extra damage on the next hit; 1 use",category:"consumable",tags:["poison","weapon","cunning"]},
  {name:"Calming Tea",desc:"Remove the Frightened condition instantly; 3 uses",category:"consumable",tags:["healing","condition"]},
  {name:"Crowfoot Powder",desc:"Inhaled by target (Near range); Wits 4+ or Blinded for 1 round",category:"consumable",tags:["control","cunning","poison"]},
  {name:"Field Kit",desc:"Bundle: 3 rations, 3 bandages, 2 torches, tinderbox",category:"gear",tags:["survival","bundle"]},
  {name:"Climbing Harness",desc:"Fall from height reduces damage by 2; Agility 4+ to catch yourself",category:"gear",tags:["climbing","safety"]},
  {name:"Folding Grapnel",desc:"Compact grappling hook; fits in a belt pouch",category:"gear",tags:["climbing","concealable"]},

  /* ── 15 Magical Items ───────────────────────────────────────────────── */
  {name:"Moonwhisper Cloak",desc:"Become invisible to all animals at will; does not affect intelligent beings",category:"magical",tags:["stealth","animals","magic"]},
  {name:"Heartwood Amulet",desc:"Once per session: automatically succeed on any one Insight roll",category:"magical",tags:["insight","magic","amulet"]},
  {name:"Storm-Seed Pouch",desc:"Holds 3 enchanted seeds; each deals 1d6+2 lightning damage on impact (Near range)",category:"magical",tags:["weapon","lightning","ranged","magic"]},
  {name:"Rootfast Boots",desc:"Cannot be moved, pushed, knocked Prone, or repositioned against your will",category:"magical",tags:["defense","magic","boots"]},
  {name:"Spiritbound Lantern",desc:"Reveals hidden and invisible spirits; spirits cannot approach within 1 zone of it",category:"magical",tags:["magic","spirit","light"]},
  {name:"Acorn of Returning",desc:"Thrown up to Far range and returns to your hand after impact; deals 1d6 damage",category:"magical",tags:["weapon","thrown","magic","ranged"]},
  {name:"Bark-Iron Bracer",desc:"Once per combat: reduce one hit to 0 damage; recharges on long rest",category:"magical",tags:["defense","magic","bracer"]},
  {name:"Echo Seed",desc:"Plant in ground; hear all speech within 2 zones of it for 24 hours",category:"magical",tags:["scouting","magic","ritual"]},
  {name:"Warden's Whistle",desc:"All creatures within 3 zones freeze for 1 round; Wits 4+ to resist; once per day",category:"magical",tags:["control","magic","once-per-day"]},
  {name:"Fatebound Ring",desc:"Once per session: reroll any single die and take the new result",category:"magical",tags:["magic","luck","ring"]},
  {name:"Silver-Tongue Signet",desc:"Presence rolls to persuade or charm auto-succeed against single targets; once per scene",category:"magical",tags:["social","magic","signet","presence"]},
  {name:"Thorn of Binding",desc:"Thrown at target (Near range); they are Rooted until they pass Brawn 5+; 2 charges per rest",category:"magical",tags:["control","magic","ranged","thorn"]},
  {name:"Dreamcatcher Net",desc:"Ensnared creatures cannot use abilities and act on instinct only; Wits 5+ to escape",category:"magical",tags:["control","magic","net"]},
  {name:"Ancestor's Skull",desc:"Hold the skull of a dead creature and ask it one yes/no question; once per day",category:"magical",tags:["magic","spirit","knowledge","once-per-day"]},
  {name:"Verdant Seed",desc:"Plant and wait one round; fills a chosen zone with full cover and difficult terrain; single use",category:"magical",tags:["control","terrain","magic","nature"]},
];

export const ITEM_CATEGORIES = [
  {key:"all",   label:"All"},
  {key:"weapon",  label:"Weapons"},
  {key:"armor",   label:"Armor"},
  {key:"gear",    label:"Gear"},
  {key:"consumable",label:"Consumables"},
  {key:"magical", label:"✦ Magical"},
];
